language: node_js

services:
  - docker

before_install:
  - docker build -t setheal/node-exercise .
  - docker run setheal/node-exercise /bin/sh -c "npm run lint; npm test"

# deploy:
#   provider: heroku
#   api_key:
#     secure: uFgT8AHz8GfdnNPTSYGLjV68spAHfFO233EZl/PnnZMmBBHxfUY9u1g2qx5agMLWNXyhiNSEtnJPxk2bR7j0RNhAnx3KW7I3tLiWLmfRLM6cH4qq9Teps8pgFsPVAieLdN6F8/2a5H4N9GmmHVBP/Z3+TzHUD3/7H7zqI7pLdb0onM8OuSNSj/IBQv19e360u866SBItrw2mEtctQjKj9UaVc5eDmV5JgH1T6+N6ghX5q+CzJRItE+YNeEkRAsWnmn1HpwBfTd+8B4S05GS+JZ50W70B/FWfmy21ioJovhsiDZGl642Znsq7gSWhTqaozrldnxz8QMJ0VtzEtM3YkUFJRmsjDxBShUShi8++o4aCb8YGk1nU8I1NKEaB+BJw90rfLZivHM0AUjY3oAmvtG8bEzLy/f5UZfY8hmAocFUt1RjYMJ8WVK3H2TwdSuwh4d1hnV68wHG3xa/M462mJzh6GTWHcpqtSKR7Box2SaEJirQwK6gaY4Oe+Auf9SBeJFZyLZDb3146eTl3lhXcqOnZ9EbHzzqqtKajmXyP3jUNpi1wuktvicY2fXEEwLBvrdRlf+oR9aM72e38Pq1UuCbL1UWgPdMUFTpcC/q0lzacvJanZqgxEhh4a2UPgFQPzBBTJvuumNv3R2S9fE2jii8XXXGSNgrBtSMiTk8MYDM=
env:
  matrix:
    secure: ZlsA165XG+aXXag/aVwaQ2+OGxdgW45mPYYxN1lEPsm5o2thn7twmtK6k2KpH0lfOoO+YjeCMmn9n0+OIFnxpHKsCW8+xuSwe7nmP45K6FaNpdOvSDYS1sIDTGduI2KhyPElFcOXzkxOoTcwxCsJuN2LB0LnRwn+ITNUQWzd/bowyOZZWp6VqpbGysD8ZNSF89RtoD9+36HA4EOiS4ksPd6WpjyA7MzictORha6vxz+rpKmqe1TGT2EzkgcvXhh7z5mwrWCdhgxq4p0FdIJeCL1NTTkfkIGBe3ki77Nqs7R/EwXBiW10sxa6tUZlH1xquke6Z3PCRIf8bVkzOjYkiKZS809OAzg7zs+NbQkRyzSF216Fb0mQMVO41jyQrFnmz8BIJNy5wAuHsMfu19FRGtKvpmh4smI8JWEzIGZ8vIH9kkOiV0B0I3pjxzQpUhcrEXt+5oyMDBjiH1xxwRlhVPL6MOKCnUzTnaoaiHuozyDN4BIRp4ILB+HSUl4JtP0bAsQAsMKqOz4Ei/niwYuFuR0Zz5CRb40yM5il+moRa6rqATm56CrcLct9qDQRHwECVWOSNaxtr0PuOXVntCf4unWP7DUM+2i3A3/dgIcSK38atgpvvqwpiKD/eTkFCgyWPQW+gGGkKogRWVb9+X3fAxGRVGv4Ylnh9eA0/P2W7QY=
